apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yml
resources:
- ../base
images:
- name: humancat-backend-image
  newName: tomcat
  newTag: latest
namespace: gitops
